#!/bin/bash

set -ex 

rm -f a.out

pushd hdrbg
./buildit
popd

DEBUG_FLAGS="-g -Og"
RELEASE_FLAGS=""
FLAGS=$RELEASE_FLAGS
#cp ../examples/monolithic_build_multilevel_native/build/mldsa/mldsa_native.S.o .
#gcc $FLAGS -DMLD_FORCE_X86_64 -mavx2 -mbmi2 -I . -I hdrbg main.c  mldsa_native.S.o hdrbg/libhdrbg.a
#gcc $FLAGS -I . -I hdrbg main.c hdrbg/libhdrbg.a

gcc $FLAGS -I . -I hdrbg main.c hdrbg/libhdrbg.a -L../test/build -lmldsa44  -lmldsa65 -lmldsa87

#./a.out mldsa87 $*