#!/bin/bash

set -ex 

rm -f a.out

pushd hdrbg
./buildit
popd

DEBUG_FLAGS="-g -Og"
RELEASE_FLAGS=""
FLAGS=$RELEASE_FLAGS
cp ../examples/monolithic_build_multilevel_native/build/mldsa/mldsa_native.S.o .
gcc $FLAGS -I . -I hdrbg main.c  mldsa_native.S.o hdrbg/libhdrbg.a
#./a.out mldsa87 $*