#!/bin/bash

set -ex

PSET=$1
HDRBG_SEED=$2
./log_aborts mldsa$PSET 69  $HDRBG_SEED ${@: 3}
./log_aborts mldsa$PSET 10K $HDRBG_SEED --only-1-repetition ${@: 3}
./log_aborts mldsa$PSET 1M  $HDRBG_SEED --only-1-repetition ${@: 3}