#!/bin/bash

set -ex

PSET=$1
HDRBG_SEED=$2
./log_aborts mldsa$PSET 10K $HDRBG_SEED --exact-repetitions --min-repetitions=1 ${@: 3}
./log_aborts mldsa$PSET 1M  $HDRBG_SEED --exact-repetitions --min-repetitions=1 ${@: 3}